"""Signal logging infrastructure for tracking alert signals and outcomes.

Records every signal generated by the alert system (GEX, PCR, max pain,
flow, webhook) with timestamps, source metadata, and optional outcome
tracking. Used for signal accuracy analysis and strategy research.

Table: signal_log (added to Store.init())
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import aiosqlite

logger = logging.getLogger(__name__)


@dataclass
class SignalEvent:
    """A single signal event to be logged.

    Attributes:
        signal_type: Type of signal (e.g., "gamma_flip", "squeeze", "flow", "webhook").
        ticker: Ticker symbol.
        direction: Signal direction ("bullish", "bearish", "neutral").
        strength: Signal strength/confidence (0.0-1.0).
        source: Source cog/system that generated the signal.
        metadata: Additional data about the signal.
        timestamp: When the signal was generated (auto-filled if None).
    """

    signal_type: str
    ticker: str
    direction: str = "neutral"
    strength: float = 0.5
    source: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime | None = None

    def __post_init__(self) -> None:
        if self.timestamp is None:
            self.timestamp = datetime.now()


class SignalLogger:
    """Logs signal events to SQLite for analysis.

    Requires a shared aiosqlite connection (from Store). Call init_table()
    to create the required table, or let Store.init() handle it.

    Usage:
        logger = SignalLogger(db)
        await logger.log_signal(SignalEvent(
            signal_type="gamma_flip",
            ticker="SPY",
            direction="bearish",
            source="cog_alerts",
        ))
    """

    def __init__(self, db: aiosqlite.Connection) -> None:
        self._db = db

    async def init_table(self) -> None:
        """Create the signal_log table if it doesn't exist."""
        await self._db.execute("""
            CREATE TABLE IF NOT EXISTS signal_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                signal_type TEXT NOT NULL,
                ticker TEXT NOT NULL,
                direction TEXT NOT NULL DEFAULT 'neutral',
                strength REAL NOT NULL DEFAULT 0.5,
                source TEXT,
                metadata TEXT DEFAULT '{}',
                outcome TEXT,
                outcome_pnl REAL,
                outcome_updated_at TEXT
            )
        """)

        await self._db.execute("""
            CREATE INDEX IF NOT EXISTS idx_signal_log_ticker_type
            ON signal_log (ticker, signal_type)
        """)

        await self._db.execute("""
            CREATE INDEX IF NOT EXISTS idx_signal_log_timestamp
            ON signal_log (timestamp)
        """)

        await self._db.commit()
        logger.debug("Signal log table initialized")

    async def log_signal(self, event: SignalEvent) -> int:
        """Log a signal event to the database.

        Args:
            event: The signal event to log.

        Returns:
            The inserted row ID.
        """
        meta_json = json.dumps(event.metadata)

        cursor = await self._db.execute(
            """
            INSERT INTO signal_log (timestamp, signal_type, ticker, direction, strength, source, metadata)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                event.timestamp.isoformat(),
                event.signal_type,
                event.ticker,
                event.direction,
                event.strength,
                event.source,
                meta_json,
            ),
        )
        await self._db.commit()

        signal_id = cursor.lastrowid
        logger.debug(
            "Logged signal #%d: %s %s %s (strength=%.2f, source=%s)",
            signal_id, event.signal_type, event.ticker, event.direction,
            event.strength, event.source,
        )
        return signal_id

    async def update_outcome(
        self,
        signal_id: int,
        outcome: str,
        pnl: float | None = None,
    ) -> None:
        """Update the outcome for a logged signal.

        Args:
            signal_id: The signal log row ID.
            outcome: Outcome description ("win", "loss", "scratch", "expired").
            pnl: Optional P&L value.
        """
        now = datetime.now().isoformat()

        await self._db.execute(
            """
            UPDATE signal_log
            SET outcome = ?, outcome_pnl = ?, outcome_updated_at = ?
            WHERE id = ?
            """,
            (outcome, pnl, now, signal_id),
        )
        await self._db.commit()

        logger.debug("Updated signal #%d outcome: %s (pnl=%s)", signal_id, outcome, pnl)

    async def get_signals(
        self,
        ticker: str | None = None,
        signal_type: str | None = None,
        limit: int = 100,
        since: datetime | None = None,
    ) -> list[dict[str, Any]]:
        """Query logged signals with optional filters.

        Args:
            ticker: Filter by ticker symbol.
            signal_type: Filter by signal type.
            limit: Maximum number of results.
            since: Only return signals after this timestamp.

        Returns:
            List of signal dicts in reverse chronological order.
        """
        conditions = []
        params: list[Any] = []

        if ticker is not None:
            conditions.append("ticker = ?")
            params.append(ticker)

        if signal_type is not None:
            conditions.append("signal_type = ?")
            params.append(signal_type)

        if since is not None:
            conditions.append("timestamp >= ?")
            params.append(since.isoformat())

        where_clause = ""
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

        query = f"""
            SELECT id, timestamp, signal_type, ticker, direction, strength,
                   source, metadata, outcome, outcome_pnl, outcome_updated_at
            FROM signal_log
            {where_clause}
            ORDER BY timestamp DESC
            LIMIT ?
        """
        params.append(limit)

        cursor = await self._db.execute(query, params)
        rows = await cursor.fetchall()

        columns = [
            "id", "timestamp", "signal_type", "ticker", "direction",
            "strength", "source", "metadata", "outcome", "outcome_pnl",
            "outcome_updated_at",
        ]

        results = []
        for row in rows:
            result = dict(zip(columns, row))
            try:
                result["metadata"] = json.loads(result["metadata"] or "{}")
            except json.JSONDecodeError:
                result["metadata"] = {}
            results.append(result)

        return results

    async def get_signal_stats(
        self,
        ticker: str | None = None,
        since: datetime | None = None,
    ) -> dict[str, Any]:
        """Get aggregate statistics for logged signals.

        Args:
            ticker: Optional ticker filter.
            since: Optional time filter.

        Returns:
            Dict with total_signals, by_type, by_direction, outcome_counts.
        """
        conditions = []
        params: list[Any] = []

        if ticker is not None:
            conditions.append("ticker = ?")
            params.append(ticker)

        if since is not None:
            conditions.append("timestamp >= ?")
            params.append(since.isoformat())

        where_clause = ""
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

        # Total count
        cursor = await self._db.execute(
            f"SELECT COUNT(*) FROM signal_log {where_clause}", params
        )
        total = (await cursor.fetchone())[0]

        # Count by type
        cursor = await self._db.execute(
            f"SELECT signal_type, COUNT(*) FROM signal_log {where_clause} GROUP BY signal_type",
            params,
        )
        by_type = dict(await cursor.fetchall())

        # Count by direction
        cursor = await self._db.execute(
            f"SELECT direction, COUNT(*) FROM signal_log {where_clause} GROUP BY direction",
            params,
        )
        by_direction = dict(await cursor.fetchall())

        # Count by outcome (only for signals with outcomes)
        outcome_where = where_clause
        outcome_params = list(params)
        if outcome_where:
            outcome_where += " AND outcome IS NOT NULL"
        else:
            outcome_where = "WHERE outcome IS NOT NULL"

        cursor = await self._db.execute(
            f"SELECT outcome, COUNT(*) FROM signal_log {outcome_where} GROUP BY outcome",
            outcome_params,
        )
        outcome_counts = dict(await cursor.fetchall())

        return {
            "total_signals": total,
            "by_type": by_type,
            "by_direction": by_direction,
            "outcome_counts": outcome_counts,
        }
