"""Data models for the risk analytics system.

All dataclasses used across the risk subsystem: Greeks aggregation,
VaR results, stress test outputs, risk alerts, and snapshots.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class PortfolioGreeks:
    """Aggregated Greeks across all open paper positions.

    Raw Greeks are summed across all legs of all open positions.
    Dollar Greeks convert to P&L sensitivity per market move.

    Attributes:
        delta: Raw portfolio delta (sum of all leg deltas * quantity * multiplier_sign).
        gamma: Raw portfolio gamma.
        theta: Portfolio theta ($/day time decay).
        vega: Portfolio vega ($ per 1 vol-point IV change).
        dollar_delta: P&L per $1 move in SPX = delta * S / 100.
        dollar_gamma: Delta change per 1% SPX move = gamma * S^2 * 0.01 / 100.
        net_premium: Total premium at risk across all positions.
        num_positions: Count of open positions.
        num_legs: Total number of option legs across all positions.
        timestamp: When Greeks were computed (ISO string).
        greeks_by_expiry: Per-expiry breakdown {expiry_iso: {delta, gamma, theta, vega}}.
        greeks_by_strategy: Per-strategy breakdown {strategy_id: {delta, gamma, theta, vega}}.
    """

    delta: float = 0.0
    gamma: float = 0.0
    theta: float = 0.0
    vega: float = 0.0
    dollar_delta: float = 0.0
    dollar_gamma: float = 0.0
    net_premium: float = 0.0
    num_positions: int = 0
    num_legs: int = 0
    timestamp: str = ""
    greeks_by_expiry: dict[str, dict[str, float]] = field(default_factory=dict)
    greeks_by_strategy: dict[str, dict[str, float]] = field(default_factory=dict)


@dataclass
class VaRResult:
    """Value at Risk computation results.

    Contains both Delta-Gamma (parametric) and Historical VaR when available.

    Attributes:
        dg_var_95: Delta-Gamma VaR at 95% confidence (positive = max loss).
        dg_var_99: Delta-Gamma VaR at 99% confidence.
        hist_var_95: Historical VaR at 95% (None if no historical data).
        hist_var_99: Historical VaR at 99%.
        cvar_95: Conditional VaR (Expected Shortfall) at 95%.
        worst_case: Worst historical scenario P&L.
        pct_of_nav_95: dg_var_95 as percentage of NAV.
        pct_of_nav_99: dg_var_99 as percentage of NAV.
        daily_vol_used: The 1-day vol forecast used for parametric VaR.
        timestamp: When VaR was computed.
    """

    dg_var_95: float = 0.0
    dg_var_99: float = 0.0
    hist_var_95: float | None = None
    hist_var_99: float | None = None
    cvar_95: float | None = None
    worst_case: float | None = None
    pct_of_nav_95: float = 0.0
    pct_of_nav_99: float = 0.0
    daily_vol_used: float = 0.0
    timestamp: str = ""


@dataclass
class StressScenario:
    """Definition of a single stress test scenario.

    Attributes:
        name: Human-readable scenario name.
        spot_shock: Fractional change in SPX price (-0.10 = -10%).
        vol_shock: Absolute change in IV (0.20 = +20 vol points).
        time_days: Days of time decay to simulate.
    """

    name: str = ""
    spot_shock: float = 0.0
    vol_shock: float = 0.0
    time_days: float = 0.0


@dataclass
class StressTestResult:
    """Result of a single stress test scenario.

    Attributes:
        scenario: The scenario that was run.
        portfolio_pnl: Dollar P&L under this scenario.
        pnl_pct_of_nav: P&L as percentage of NAV.
        status: "ok", "warn" (>5% NAV loss), or "breach" (>10% NAV loss).
        position_pnls: Per-position P&L breakdown {position_id: pnl}.
    """

    scenario: StressScenario = field(default_factory=StressScenario)
    portfolio_pnl: float = 0.0
    pnl_pct_of_nav: float = 0.0
    status: str = "ok"
    position_pnls: dict[int, float] = field(default_factory=dict)


@dataclass
class RiskAlert:
    """Alert generated by portfolio risk monitoring.

    Attributes:
        level: Severity -- "info", "warning", "breach", "circuit_breaker".
        category: Risk type -- "delta", "gamma", "vega", "theta", "var",
                  "drawdown", "daily_loss", "concentration", "correlation",
                  "vix", "anomaly", "cash_reserve".
        message: Human-readable alert description.
        current_value: Current metric value.
        limit_value: The limit that was approached or breached.
        utilization_pct: current_value / limit_value * 100.
        timestamp: ISO timestamp.
    """

    level: str = "info"
    category: str = ""
    message: str = ""
    current_value: float = 0.0
    limit_value: float = 0.0
    utilization_pct: float = 0.0
    timestamp: str = ""


@dataclass
class RiskCheckResult:
    """Result of pre-trade risk validation.

    Returned by RiskManager.check_order() to approve or reject an order.

    Attributes:
        approved: Whether the order passed all checks.
        checks_passed: List of check names that passed.
        checks_failed: List of check names that failed.
        reasons: Human-readable rejection reasons (empty if approved).
        adjusted_size: If size was reduced to fit limits (None if unchanged).
        regime_state: Current regime state used for checks (0/1/2).
        regime_name: "risk-on", "risk-off", or "crisis".
    """

    approved: bool = False
    checks_passed: list[str] = field(default_factory=list)
    checks_failed: list[str] = field(default_factory=list)
    reasons: list[str] = field(default_factory=list)
    adjusted_size: float | None = None
    regime_state: int = 0
    regime_name: str = "risk-on"


@dataclass
class PositionSizeResult:
    """Result of position sizing computation.

    Attributes:
        max_premium: Maximum premium to deploy (USD).
        max_contracts: Estimated max contracts (premium / avg_premium_per_contract).
        kelly_raw: Raw Kelly fraction (before scaling).
        kelly_fraction: Scaled Kelly fraction applied.
        regime_multiplier: Regime-based scaling factor.
        vol_multiplier: Vol-based scaling factor.
        anomaly_multiplier: Anomaly-based scaling factor.
        rationale: Human-readable sizing explanation.
    """

    max_premium: float = 0.0
    max_contracts: int = 0
    kelly_raw: float = 0.0
    kelly_fraction: float = 0.0
    regime_multiplier: float = 1.0
    vol_multiplier: float = 1.0
    anomaly_multiplier: float = 1.0
    rationale: str = ""


@dataclass
class ConcentrationReport:
    """Portfolio concentration analysis.

    Attributes:
        by_expiry: {expiry_iso: {delta_pct, premium_pct, position_count}}.
        by_strategy: {strategy_id: {delta_pct, premium_pct, position_count}}.
        by_strike_range: {range_label: {delta_pct, premium_pct}} for 25-pt ranges.
        max_expiry_concentration: Highest single-expiry delta percentage.
        max_strategy_concentration: Highest single-strategy premium percentage.
        max_strike_concentration: Highest single-range premium percentage.
        warnings: List of concentration warnings.
    """

    by_expiry: dict[str, dict[str, float]] = field(default_factory=dict)
    by_strategy: dict[str, dict[str, float]] = field(default_factory=dict)
    by_strike_range: dict[str, dict[str, float]] = field(default_factory=dict)
    max_expiry_concentration: float = 0.0
    max_strategy_concentration: float = 0.0
    max_strike_concentration: float = 0.0
    warnings: list[str] = field(default_factory=list)


@dataclass
class CorrelationReport:
    """Cross-strategy correlation analysis.

    Attributes:
        pnl_correlation: Pairwise PnL correlation matrix {(id_a, id_b): corr}.
        greeks_similarity: Pairwise Greeks cosine similarity {(id_a, id_b): sim}.
        high_correlation_pairs: Pairs with correlation >= high threshold.
        moderate_correlation_pairs: Pairs with correlation >= moderate threshold.
        warnings: Human-readable correlation warnings.
    """

    pnl_correlation: dict[tuple[int, int], float] = field(default_factory=dict)
    greeks_similarity: dict[tuple[int, int], float] = field(default_factory=dict)
    high_correlation_pairs: list[tuple[int, int, float]] = field(default_factory=list)
    moderate_correlation_pairs: list[tuple[int, int, float]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class RiskSnapshot:
    """Complete risk state for reporting and persistence.

    Generated on-demand or at each monitoring cycle. Contains every risk
    metric needed for Discord reporting and audit trail.

    Attributes:
        portfolio_greeks: Aggregated Greeks.
        var_result: VaR computation results.
        stress_results: Results of all stress scenarios.
        concentration: Concentration analysis.
        active_alerts: Currently active risk alerts.
        circuit_breakers_active: Names of active circuit breakers.
        regime_state: Current HMM regime state (0/1/2).
        regime_name: "risk-on", "risk-off", or "crisis".
        anomaly_score: Current composite anomaly score.
        nav: Current portfolio NAV.
        risk_utilization: {category: utilization_pct} for each limit.
        timestamp: ISO timestamp.
    """

    portfolio_greeks: PortfolioGreeks = field(default_factory=PortfolioGreeks)
    var_result: VaRResult = field(default_factory=VaRResult)
    stress_results: list[StressTestResult] = field(default_factory=list)
    concentration: ConcentrationReport = field(default_factory=ConcentrationReport)
    active_alerts: list[RiskAlert] = field(default_factory=list)
    circuit_breakers_active: list[str] = field(default_factory=list)
    regime_state: int = 0
    regime_name: str = "risk-on"
    anomaly_score: float = 0.0
    nav: float = 0.0
    risk_utilization: dict[str, float] = field(default_factory=dict)
    timestamp: str = ""
